### ISSUE TITLE
Organisation-level adoption of open source

### ISSUE THREAD

**Issue by wbryant** [nhsx/open-source-policy#13]
Could this include a section on promoting organisation-level adoption of these practices, and potentially (probably separately) a playbook around required ICT infrastructure/personnel required to support this in a sustainable way?

**Comment by otlah** [comment]
We've got a playbook coming out this spring (stay tuned!) for different kinds of open source challenge, including a couple of case studies that respond to sustainability and maintenance issues. Once the playbook is published we'll be able to link from the policy to those particular projects and programmes. It's a very broad subject though, so stewardship, custodianship and maintenance models are all part of our ongoing work through 22/23. 

Adoption is an even broader issue, and is essentially our whole programme! We'll reflect that work here where we can, but not everything is a good fit for policy. Whether or not we need to publish an open source _strategy_ is an ongoing question, but if we do it'll live here too.
