### ISSUE TITLE
Open data/data standards

### ISSUE THREAD

**Issue by wbryant** [nhsx/open-source-policy#14]
One of the biggest challenges in sharing code for clinical research/analytics is consistent data models.  This can be addressed by bespoke per-project data engineering or institutional adoption of a standard data model (e.g. OMOP/FHIR) or (more likely) a combination of the two.

In order to promote open tools, challenges around data standards and interoperability need to be addressed - this should at least be referenced here.  It addresses the same "never the same job twice" advantage of open sourcing and indeed is a prerequisite for sharable analytics code.

**Comment by otlah** [comment]
100% agreed. A lot of the push for this policy is related to our new data strategy which speaks to many of those challenges, and I sit within our Standards and Interoperability team. I'm very happy to reference both of those facts and our wider work right at the top.
