### ISSUE TITLE
Existing Open source software in use in Health and Care

### ISSUE THREAD

**Issue by simplybenuk** [nhsx/open-source-policy#17]
I'm not sure if this exists or not, but it would be great if there were a list of all the open source software in use across the NHS and who is using it and for what.

For example, I was looking at open source analytical tools such as [Matomo](https://github.com/matomo-org/matomo) the other day and it would be really useful to have a list of people who may have already been using it to get their lessons learned before implementation.

Having such a list may also encourage open source uptake as people realise they are not alone.

**Comment by otlah** [comment]
Hi Ben, I very much agree that there's a real lack of awareness around how much open source work is produced and consumed in the NHS, and that's something we're looking into. It's more of a companion piece to the policy than something to be included within it, but stay tuned for some useful resources later this year!
